---

- name: Download nodeexporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-{{node_exporter_cpu_arch}}.tar.gz"
    dest: /tmp/

- name: Extract nodeexporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-{{node_exporter_cpu_arch}}.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy file
  copy: 
    src: /tmp/node_exporter-{{node_exporter_version}}.linux-amd64/node_exporter
    remote_src: true
    dest: /usr/local/bin
    mode: '0755'

- name: Create group
  group: 
    name: node_exporter
    state: present

- name: Create user
  user:
    name: node_exporter
    shell: /bin/false
    group: node_exporter

- name: Copy systemd service-unit file
  copy: 
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: start node_exporter
  systemd: 
    state: started 
    enabled: true
    name: node_exporter
    daemon_reload: yes
    